export const TEACHER_PERMISSIONS = [
  'TEACHER_PROFILE_READ',
  'TEACHER_SCHEDULE_READ',
  'TEACHER_STUDENT_READ',
  'ATTENDANCE_WRITE',
  'LESSON_COMPLETE',
  'LESSON_REVERSE_OWN_WINDOW',
  'FEEDBACK_WRITE',
  'TEACHING_RECORD_READ',
  'LESSON_LEDGER_READ_OWN',
  'TEACHER_EARNING_READ_OWN',
  'TEACHER_WITHDRAWAL_READ_OWN',
  'TEACHER_WITHDRAWAL_CREATE',
  'TEACHER_WITHDRAWAL_CANCEL_OWN',
  'TEACHER_GROUP_CAMPAIGN_READ',
] as const;

export const EARNING_MANAGEMENT_PERMISSIONS = [
  'EARNING_RULE_MANAGE',
  'TEACHER_EARNING_REVIEW',
  'PARTNER_EARNING_RULE_MANAGE',
  'PARTNER_EARNING_REVIEW',
  'WITHDRAWAL_REVIEW',
  'WITHDRAWAL_MARK_PAID',
] as const;

export const SUPER_ADMIN_PERMISSIONS = [
  'FINANCE_CORRECTION_REVIEW',
  'FINANCE_REFUND_REVIEW',
  'GLOBAL_DASHBOARD_READ',
  'GLOBAL_CAMPUS_READ',
  'GLOBAL_CAMPUS_MAP_MANAGE',
  'GLOBAL_STUDENT_READ',
  'STAFF_ACCOUNT_MANAGE',
  'GLOBAL_ROSTER_MANAGE',
  'GLOBAL_ROSTER_EXPORT',
  'COURSE_PACKAGE_VALIDITY_MANAGE',
  'GLOBAL_LEDGER_READ',
  'LESSON_LEDGER_ADJUST',
  'GLOBAL_SETTINGS_READ',
  'ROLE_PERMISSION_READ',
  'AUDIT_LOG_READ',
  'COURSE_PRODUCT_MANAGE',
  'ENROLLMENT_ORDER_REVIEW',
  'ENROLLMENT_ORDER_VOID',
  'GROUP_CAMPAIGN_MANAGE',
  'GROUP_ORDER_READ',
  'GROUP_REFUND_MANAGE',
] as const;

export const PARENT_PERMISSIONS = [
  'PARENT_PROFILE_READ',
  'PARENT_PROFILE_WRITE',
  'PARENT_CAMPUS_DIRECTORY_READ',
  'PARENT_HOME_READ',
  'PARENT_HOURS_READ',
  'PARENT_LEAVE_READ',
  'PARENT_LEAVE_WRITE',
  'PARENT_UPDATES_READ',
  'PARENT_COURSE_PRODUCT_READ',
  'PARENT_ENROLLMENT_ORDER_CREATE',
  'PARENT_ENROLLMENT_ORDER_READ_OWN',
  'PARENT_PAYMENT_PROOF_UPLOAD_OWN',
  'PARENT_ENROLLMENT_ORDER_CANCEL_OWN',
  'PARENT_GROUP_CAMPAIGN_READ',
  'PARENT_GROUP_ORDER_READ_OWN',
  'PARENT_GROUP_JOIN',
] as const;

export const CAMPUS_MANAGER_PERMISSIONS = [
  'CAMPUS_DASHBOARD_READ',
  'CAMPUS_STUDENT_READ',
  'CAMPUS_STUDENT_CREATE',
  'CAMPUS_ROSTER_MANAGE',
  'CAMPUS_ROSTER_EXPORT',
  'CAMPUS_SCHEDULE_READ',
  'CAMPUS_SCHEDULE_CREATE',
  'CAMPUS_SCHEDULE_UPDATE',
  'CAMPUS_LEAVE_REVIEW',
  'CAMPUS_WARNING_READ',
  'CAMPUS_SETTINGS_READ',
  'CAMPUS_SETTINGS_UPDATE',
] as const;

export const PARTNER_PERMISSIONS = [
  'PARTNER_DASHBOARD_READ',
  'PARTNER_PROFILE_READ',
  'PARTNER_STUDENT_READ',
  'PARTNER_WARNING_READ',
  'PARTNER_ATTENDANCE_READ',
  'PARTNER_TEACHER_READ',
  'PARTNER_LEDGER_READ',
  'PARTNER_EARNING_READ',
  'PARTNER_GROUP_CAMPAIGN_READ',
] as const;

export const FINANCE_PERMISSIONS = [
  'FINANCE_CORRECTION_READ',
  'FINANCE_CORRECTION_WRITE',
  'FINANCE_CORRECTION_APPLY',
  'FINANCE_REPORT_READ',
  'FINANCE_REPORT_EXPORT',
  'FINANCE_REFUND_READ',
  'FINANCE_REFUND_WRITE',
  'FINANCE_REFUND_PAY',
  'FINANCE_RECEIPT_READ',
  'FINANCE_RECEIPT_EXPORT',
  'FINANCE_RECEIPT_WRITE',
  'FINANCE_PACKAGE_ISSUE',
  'FINANCE_OVERSIGHT_READ',
  'FINANCE_OVERSIGHT_EXPORT',
] as const;

export const HR_PERMISSIONS = [
  'HR_TEACHER_READ',
  'HR_TEACHER_RECORD_WRITE',
  'HR_REPORT_READ',
  'HR_REPORT_EXPORT',
] as const;

export const PERMISSIONS = [
  ...HR_PERMISSIONS,
  ...FINANCE_PERMISSIONS,
  ...TEACHER_PERMISSIONS,
  ...PARENT_PERMISSIONS,
  ...PARTNER_PERMISSIONS,
  ...CAMPUS_MANAGER_PERMISSIONS,
  ...EARNING_MANAGEMENT_PERMISSIONS,
  ...SUPER_ADMIN_PERMISSIONS,
] as const;

export type Permission = (typeof PERMISSIONS)[number];
