import type { RoleCode } from '../../common/auth/authenticated-user';
import {
  CAMPUS_MANAGER_PERMISSIONS,
  FINANCE_PERMISSIONS,
  HR_PERMISSIONS,
  EARNING_MANAGEMENT_PERMISSIONS,
  PARTNER_PERMISSIONS,
  PARENT_PERMISSIONS,
  Permission,
  SUPER_ADMIN_PERMISSIONS,
  TEACHER_PERMISSIONS,
} from './permissions.constants';

export const ROLE_PERMISSION_MATRIX: Readonly<
  Record<RoleCode, readonly Permission[]>
> = {
  PARENT: PARENT_PERMISSIONS,
  PARTNER: PARTNER_PERMISSIONS,
  TEACHER: TEACHER_PERMISSIONS,
  OPERATOR: [],
  HR: HR_PERMISSIONS,
  FINANCE: FINANCE_PERMISSIONS,
  CAMPUS_MANAGER: CAMPUS_MANAGER_PERMISSIONS,
  SUPER_ADMIN: [
    ...TEACHER_PERMISSIONS,
    ...PARENT_PERMISSIONS,
    ...EARNING_MANAGEMENT_PERMISSIONS,
    ...SUPER_ADMIN_PERMISSIONS,
  ],
};
