import { superAdminService } from '../../../services/super-admin-runtime';
import { SuperAdminWithdrawal } from '../../../types/super-admin';
import { createMutationKey, formatLocalDateTime, formatMoneyFen } from '../../../utils/super-admin-format';

Page({
  data: { viewState: 'loading', errorMessage: '', reason: '', payoutReference: '', payoutProofFileId: '', proofName: '', submittingId: '', withdrawals: [] as Array<SuperAdminWithdrawal & { amountLabel: string; timeLabel: string; statusLabel: string }> },
  onLoad() { void this.load(); },
  onReasonInput(event: WechatMiniprogram.Input) { this.setData({ reason: event.detail.value }); },
  onReferenceInput(event: WechatMiniprogram.Input) { this.setData({ payoutReference: event.detail.value }); },
  async load() { const state = await superAdminService.loadWithdrawals({ page: 1, pageSize: 100 }); if (state.status === 'success' || state.status === 'empty') this.setData({ viewState: state.status, withdrawals: state.data.data.map((item) => ({ ...item, amountLabel: formatMoneyFen(item.amountFen), timeLabel: formatLocalDateTime(item.requestedAt), statusLabel: { SUBMITTED: '待审核', APPROVED: '已批准', PAYING: '打款中', PAID: '已完成', CANCELLED: '已取消', REJECTED: '已驳回', FAILED: '打款失败' }[item.status] })) }); else if (state.status === 'error') this.setData({ viewState: state.statusCode === 403 ? 'forbidden' : 'error', errorMessage: state.message }); },
  async onAction(event: WechatMiniprogram.TouchEvent) { const id = String(event.currentTarget.dataset.id ?? ''); const action = String(event.currentTarget.dataset.action ?? '') as 'approve' | 'reject' | 'mark-paying' | 'mark-failed'; const version = Number(event.currentTarget.dataset.version); const needsReason = action === 'reject' || action === 'mark-failed'; const reason = needsReason ? this.data.reason.trim() : undefined; if (needsReason && !reason) { wx.showToast({ title: '请填写原因', icon: 'none' }); return; } this.setData({ submittingId: id }); const state = await superAdminService.transitionWithdrawal(id, action, version, reason, createMutationKey(`withdrawal-${action}`)); this.setData({ submittingId: '' }); if (state.status === 'success') void this.load(); else if (state.status === 'error') wx.showToast({ title: state.message, icon: 'none' }); },
  onChooseProof() { wx.chooseMessageFile({ count: 1, type: 'file', extension: ['jpg', 'jpeg', 'png', 'pdf'], success: (result) => { const file = result.tempFiles[0]; if (!file) return; void this.uploadProof(file.path, file.name); } }); },
  async uploadProof(filePath: string, fileName: string) { wx.showLoading({ title: '上传凭证' }); const state = await superAdminService.uploadPayoutProof(filePath); wx.hideLoading(); if (state.status === 'success') this.setData({ payoutProofFileId: state.data.id, proofName: fileName }); else if (state.status === 'error') wx.showToast({ title: state.message, icon: 'none' }); },
  async onMarkPaid(event: WechatMiniprogram.TouchEvent) { const reference = this.data.payoutReference.trim(); if (!reference || !this.data.payoutProofFileId) { wx.showToast({ title: '请填写流水号并上传凭证', icon: 'none' }); return; } const id = String(event.currentTarget.dataset.id ?? ''); const version = Number(event.currentTarget.dataset.version); this.setData({ submittingId: id }); const state = await superAdminService.markWithdrawalPaid(id, version, reference, this.data.payoutProofFileId, createMutationKey('withdrawal-paid')); this.setData({ submittingId: '' }); if (state.status === 'success') { this.setData({ payoutReference: '', payoutProofFileId: '', proofName: '' }); void this.load(); } else if (state.status === 'error') wx.showToast({ title: state.message, icon: 'none' }); },
  onRetry() { void this.load(); },
});
